//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Devfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblStatistic
    {
        public int StatisticID { get; set; }
        public string StatisticName { get; set; }
        public Nullable<decimal> StatisticValue { get; set; }
        public string StatisticUrl { get; set; }
    }
}
